name: Defender workflow
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to scan'
        required: true
        default: 'vulnerables/cve-2017-7494'

jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
#      - name: Build and Tag Image
#        run: |
#          echo "github.sha=$GITHUB_SHA"
#          docker build -t githubdemo1.azurecr.io/k8sdemo:${{ github.sha }} .

      - uses: Azure/container-scan@v0 
        name: Scan image for vulnerabilities
        id: container-scan
        continue-on-error: true
        with:
          image-name: ${{ github.event.inputs.image }}

#      - name: Push Docker image 
#        run: |
#          docker push githubdemo1.azurecr.io/k8sdemo:${{ github.sha }}

 #     - name: Post logs to appinsights
 #       uses: Azure/publish-security-assessments@v0
 #       with: 
 #         scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
 #         connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
 #         subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
