name: Deploy App B

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to deploy'
        required: false
        default: 'main'
        type: string
      trigger_dependent_workflows:
        description: 'Trigger dependent workflows?'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  deploy-app-b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Deploy App B
        run: |
          echo "Deploying App B from ref: ${{ inputs.ref }}"
          echo "Current commit: ${{ github.sha }}"
          echo "Triggered by dependent workflow: ${{ inputs.trigger_dependent_workflows }}"
