# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
name: 'Federated identity'

on:
  workflow_dispatch:
  
permissions:
  id-token: write

jobs:
  Development:
    environment: dev
    runs-on: windows-latest
    steps:
      - name: Deployment script
        run: |
          echo "Deploying to development"
          
      - name: Installing CLI-beta for OpenID Connect
        run: |
          cd ../..
          $CWD = Convert-Path .
          echo $CWD
          python --version
          python -m venv oidc-venv
          . .\oidc-venv\Scripts\Activate.ps1
          python -m pip install -q --upgrade pip
          echo "started installing cli beta" 
          pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
          echo "installed cli beta" 
          echo "$CWD\oidc-venv\Scripts" >> $env:GITHUB_PATH

      - name: Installing Az.accounts for powershell
        shell: pwsh
        run: |
             Install-Module -Name Az.Accounts -Force -AllowClobber -Repository PSGallery

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
          enable-AzPSSession: true

      - run: |
          az group list -o table

      - shell: pwsh
        run: |
          Get-AzResourceGroup
