name: Secrets

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build script
        shell: powershell
        run: |
          $secret = "${{ secrets.TARGET_URL }}"
          echo $secret.Substring(0,4) + "<space>" + $secret.Substring(4)

  Development:
    environment: dev
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deployment script
        shell: powershell
        run: |
          echo "Deploying to development"
          $secret = "${{ secrets.TARGET_URL }}"
          echo $secret.Substring(0,4) + "<space>" + $secret.Substring(4)

  Test:
    environment: test
    needs: Development
    runs-on: ubuntu-latest
    steps:
      - name: Deployment script
        shell: powershell
        run: |
          echo "Deploying to test"
          $secret = "${{ secrets.TARGET_URL }}"
          echo $secret.Substring(0,4) + "<space>" + $secret.Substring(4)

  Production:
    environment: production
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment script
        shell: powershell
        run: |
          echo "Deploying to prod"
          $secret = "${{ secrets.TARGET_URL }}"
          echo $secret.Substring(0,4) + "<space>" + $secret.Substring(4)
